
<?php
phpinfo();
//ESTE ARCHIVO ES PARA VER SI EL SERVIDOR ESTA CONFIGURADO CORRECTAMENTE
//PARA PHP, SI NO SE VE NADA, ES QUE NO ESTA CONFIGURADO CORRECTAMENTE
//SI SE VE UNA PAGINA CON INFORMACION DE PHP, ES QUE ESTA CONFIGURADO CORRECTAMENTE
//SI SE VE UN ERROR, ES QUE HAY UN ERROR EN EL SERVIDOR
?>